import "./globals.css";
import LoginButton from "@/components/auth/login-button";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutButton from "@/components/auth/profile-card";
import ProfileCard from "@/components/auth/profile-card";
import Link from "next/link";
import { getServerSession } from "next-auth";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session = await getServerSession(authOptions);
  return (
    <html lang="en" className="w-full h-full">
      <body className="w-full h-full">
        <div className="flex justify-between gap-5 text-4xl font-bold">
          <div className="flex gap-5 m-5">
            <Link href="/">Home</Link>
            <Link href="/post">Post</Link>
            <Link href="/test">Test</Link>
          </div>
          <div className="flex gap-5 m-5">
            {session?
            <span className="flex flex-wrap content-center text-xl">{session.user?.name}</span>
            : null
            }
            {session?
            <ProfileCard session={session}/> : 
            <LoginButton />}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
